
services:
  app:
    image: node:20
    volumes:
      - .:/opt/app
    working_dir: /opt/app
  dev:
    image: node:20
    volumes:
      - .:/opt/app
    working_dir: /opt/app
    command: bash -lc "yarn start"
    ports:
      - "9000:9000"
  nginx:
    image: nginx:alpine
    volumes:
      - ./dist:/usr/share/nginx/html:ro
    ports:
      - "8030:80"
    restart: unless-stopped
    
